### ISSUE TITLE
Review and clean up the Shards API Documentation

### ISSUE THREAD

**Issue by ChelseaChX** [fragcolor-xyz/shards-examples#48]
- [ ] Review all the API documentation
- [ ] Note down any empty fields/segments
- [ ] Rework any segment that is unclear
- [ ] Fix grammatical and spelling errors
